
import static org.junit.Assert.*;

import org.junit.Test;

import hanto.HantoGameFactory;
import hanto.common.HantoCoordinate;
import hanto.common.HantoException;
import hanto.common.HantoGame;
import hanto.common.HantoGameID;
import hanto.common.HantoPiece;
import hanto.common.HantoPieceType;
import hanto.common.HantoPlayerColor;
import hanto.common.MoveResult;
import hanto.kcbtsb.alpha.HantoGameAlpha;
import hanto.kcbtsb.common.HantoCell;
import hanto.kcbtsb.common.HantoCellManager;
import hanto.kcbtsb.common.HantoGameManager;
import hanto.kcbtsb.common.HantoPieceFactory;
import hanto.kcbtsb.common.HantoPlayer;
import junit.framework.TestCase;

/**
 * The class <code>HantoCellManagerTest</code> contains tests for the class
 * {@link <code>HantoCellManager</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 9/9/14 4:37 PM
 *
 * @author Kyle
 *
 * @version $Revision$
 */
public class HantoGameAlphaTest{

	
	@Test
	public void blueShouldPlaceButterfly() throws HantoException {
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		MoveResult result = HantoGameManager.bluePlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(0,0));
		assertTrue("Should place butterfly: ", result == MoveResult.OK);
	}
	
	@Test(expected=HantoException.class)
	public void exceptionRedShouldFailFirstMove() throws HantoException {
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		HantoGameManager.redPlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(0,0));
	}
	
	@Test(expected=HantoException.class)
	public void exceptionRedShouldFailPlaceButterfly() throws HantoException {
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		HantoGameManager.bluePlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(0,0));
		HantoGameManager.redPlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(0,0));
	}
	
	@Test(expected=HantoException.class)
	public void exceptionBlueShouldFailPlaceButterfly() throws HantoException {
		HantoGameFactory.getInstance();
	    HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		HantoGameManager.bluePlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(1, 1));
	}
	
	@Test
	public void redShouldPlaceButterflyAndDraw() throws HantoException {
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		HantoGameManager.bluePlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(0, 0));
		MoveResult result = HantoGameManager.redPlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(1, 1));
		assertTrue("Should place butterfly: ", result == MoveResult.DRAW);
	}
	
	@Test(expected=HantoException.class)
	public void exceptionRedShouldFailPlaceNonContiguousButterfly() throws HantoException {
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		HantoGameManager.bluePlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(0, 0));
		MoveResult result = HantoGameManager.redPlayer.placePiece(HantoPieceType.BUTTERFLY, new HantoCell(2, 1));
	}
	
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = 
 * package.sourceFolder = Hanto2014-Master/test
 * superclassType = junit.framework.TestCase
 * testCase = HantoCellManagerTest
 * testClassType = hanto.kcbtsb.alpha.HantoCellManager
 */