package hanto.kcbtsb.common;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import common.HantoTestGame;
import common.HantoTestGameFactory;

import hanto.common.HantoGameID;
import hanto.common.HantoPieceType;
import hanto.kcbtsb.HantoGameFactory;
import hanto.kcbtsb.common.HantoGameManager;
import hanto.kcbtsb.gamma.GammaHantoTestGame;

/**
 * The class <code>HantoCellManagerTest</code> contains tests for the class
 * {@link <code>HantoCellManager</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 9/9/14 4:37 PM
 *
 * @author Kyle
 *
 * @version $Revision$
 */
public class HantoCellManagerTest{

	private static HantoTestGameFactory factory;
	private HantoTestGame game;
	
	@BeforeClass
	public static void initializeClass()
	{
		factory = HantoTestGameFactory.getInstance();
	}
	
	@Before
	public void setup()
	{
		// By default, blue moves first.
		game = (GammaHantoTestGame) factory.makeHantoTestGame(HantoGameID.GAMMA_HANTO);
	}
	
	@Test
	public void hantoCellShouldBeOccupied() {
		HantoGameManager manager = HantoGameManager.getInstance();
		manager.getCellManager().addCell(0, 0);
		assertTrue("Should be occupied: ", manager.getCellManager().isCellOccupied(0, 0));
	}
	
	@Test
	public void hantoCellShouldNotBeOccupied() {
		HantoGameManager manager = HantoGameManager.getInstance();
		manager.getCellManager().addCell(0, 0);
		assertFalse("Should not be occupied: ", manager.getCellManager().isCellOccupied(1, 1));
	}
	
	@Test
	public void hantoCellShouldBeOccupiedWithBlueButterfly() {
		HantoGameManager manager = HantoGameManager.getInstance();
		HantoCell firstCell = new HantoCell(0, 0, HantoPieceType.BUTTERFLY);
		manager.getCellManager().addCell(firstCell);
		assertTrue(firstCell.getPiece() == manager.getCellManager().getCellPiece(firstCell));
		assertTrue(firstCell.getCellColor() == manager.getCellManager().getCellColor(firstCell));
		assertTrue(firstCell.getCellColor() == manager.getCellManager().getCellColor(firstCell.getX(), firstCell.getY()));
	}
	
	@Test
	public void hantoCellShouldBeEmptyAfterRemoval() {
		HantoGameManager manager = HantoGameManager.getInstance();
		HantoCell firstCell = new HantoCell(0, 0, HantoPieceType.BUTTERFLY);
		manager.getCellManager().addCell(firstCell);
		manager.getCellManager().remCell(firstCell.getX(), firstCell.getY());
		assertTrue(manager.getCellManager().findCell(firstCell) == null);
	}
	
	
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = 
 * package.sourceFolder = Hanto2014-Master/test
 * superclassType = junit.framework.TestCase
 * testCase = HantoCellManagerTest
 * testClassType = hanto.kcbtsb.alpha.HantoCellManager
 */