package hanto.kcbtsb.common;

import static org.junit.Assert.*;

import org.junit.Test;

import hanto.common.HantoGameID;
import hanto.kcbtsb.HantoGameFactory;
import hanto.kcbtsb.common.HantoGameManager;

/**
 * The class <code>HantoCellManagerTest</code> contains tests for the class
 * {@link <code>HantoCellManager</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 9/9/14 4:37 PM
 *
 * @author Kyle
 *
 * @version $Revision$
 */
public class HantoCellManagerTest{

	
	@Test
	public void hantoCellShouldBeOccupied() {
		HantoGameManager manager = HantoGameManager.getInstance();
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		manager.getCellManager().addCell(0, 0);
		assertTrue("Should be occupied: ", manager.getCellManager().isCellOccupied(0, 0));
	}
	
	@Test
	public void hantoCellShouldNotBeOccupied() {
		HantoGameManager manager = HantoGameManager.getInstance();
		HantoGameFactory.getInstance();
		HantoGameFactory.makeHantoGame(HantoGameID.ALPHA_HANTO);
		manager.getCellManager().addCell(0, 0);
		assertFalse("Should not be occupied: ", manager.getCellManager().isCellOccupied(1, 1));
	}
	
	
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = 
 * package.sourceFolder = Hanto2014-Master/test
 * superclassType = junit.framework.TestCase
 * testCase = HantoCellManagerTest
 * testClassType = hanto.kcbtsb.alpha.HantoCellManager
 */